apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: portfolio-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.20-192.168.0.25
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: portfolio-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - portfolio-ip-pool

